# Generated by Django 4.0.5 on 2022-07-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='en',
            new_name='enenrollment',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem',
            new_name='ic',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
