# Generated by Django 4.0.5 on 2022-07-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_en_student_enenrollment_rename_sem_student_ic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enenrollment',
            new_name='enrollment',
        ),
    ]
