# Generated by Django 4.0.5 on 2022-07-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_enenrollment_student_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imca1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=20)),
                ('ic', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'facalty',
            },
        ),
    ]
