# Generated by Django 4.0.5 on 2022-07-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_imca1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(max_length=4)),
                ('subject1', models.CharField(max_length=15)),
                ('subject2', models.CharField(max_length=15)),
                ('subject3', models.CharField(max_length=15)),
                ('subject4', models.CharField(max_length=15)),
                ('subject5', models.CharField(max_length=15)),
                ('subject6', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.DeleteModel(
            name='Imca1',
        ),
    ]
