# Generated by Django 4.0.5 on 2022-07-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_faculty_delete_imca1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
