# Generated by Django 4.0.5 on 2022-07-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_faculty_semester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty',
            new_name='Faculties',
        ),
        migrations.AlterModelTable(
            name='faculties',
            table='faculties',
        ),
    ]
