# Generated by Django 4.0.5 on 2022-07-05 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_faculty_faculties_alter_faculties_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculties',
        ),
    ]
