# Generated by Django 4.0.5 on 2022-07-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_lecturer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
