# Generated by Django 4.0.5 on 2022-07-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('subject1', models.CharField(max_length=15)),
                ('subject2', models.CharField(max_length=15)),
                ('subject3', models.CharField(max_length=15)),
                ('subject4', models.CharField(max_length=15)),
                ('subject5', models.CharField(max_length=15)),
                ('subject6', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'lecturer',
            },
        ),
    ]
