# Generated by Django 4.0.5 on 2022-07-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='subject1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='subject2',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='subject3',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='subject4',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='subject5',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='subject6',
            field=models.CharField(max_length=25),
        ),
    ]
