# Generated by Django 4.0.5 on 2022-07-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_lecturer_subject1_alter_lecturer_subject2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'myadmin',
            },
        ),
    ]
