# Generated by Django 4.0.5 on 2022-07-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_myadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ic3_2638601',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField()),
                ('pr', models.IntegerField(verbose_name=2)),
                ('pe', models.IntegerField(verbose_name=2)),
                ('sk', models.IntegerField(verbose_name=2)),
                ('mt', models.IntegerField(verbose_name=2)),
                ('ms', models.IntegerField(verbose_name=2)),
                ('pa', models.IntegerField(verbose_name=2)),
                ('cs', models.IntegerField(verbose_name=2)),
                ('ps', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic3_2638601',
            },
        ),
    ]
