# Generated by Django 4.0.5 on 2022-07-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_ic3_2638601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ic3_2638601',
            old_name='cs',
            new_name='cs2638601',
        ),
        migrations.RenameField(
            model_name='ic3_2638601',
            old_name='ms',
            new_name='ms2638601',
        ),
        migrations.RenameField(
            model_name='ic3_2638601',
            old_name='mt',
            new_name='mt2638601',
        ),
        migrations.RenameField(
            model_name='ic3_2638601',
            old_name='pa',
            new_name='pa2638601',
        ),
        migrations.RenameField(
            model_name='ic3_2638601',
            old_name='pe',
            new_name='pe2638601',
        ),
        migrations.RenameField(
            model_name='ic3_2638601',
            old_name='pr',
            new_name='pr2638601',
        ),
        migrations.RenameField(
            model_name='ic3_2638601',
            old_name='ps',
            new_name='ps2638601',
        ),
        migrations.RenameField(
            model_name='ic3_2638601',
            old_name='sk',
            new_name='sk2638601',
        ),
    ]
