# Generated by Django 4.0.5 on 2022-07-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_cs_ic3_2638601_cs2638601_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ic3_2638601',
            name='pr2638601',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='ic3_2638601',
            name='std_id',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
