# Generated by Django 4.0.5 on 2022-07-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_ic3_2638601_pr2638601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ic3_2638601',
            name='pr2638601',
            field=models.IntegerField(verbose_name='2'),
        ),
    ]
