# Generated by Django 4.0.5 on 2022-07-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_ic3_2638601_pr2638601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ic3_2638602',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2638602', models.IntegerField(verbose_name=2)),
                ('pe2638602', models.IntegerField(verbose_name=2)),
                ('sk2638602', models.IntegerField(verbose_name=2)),
                ('mt2638602', models.IntegerField(verbose_name=2)),
                ('ms2638602', models.IntegerField(verbose_name=2)),
                ('pa2638602', models.IntegerField(verbose_name=2)),
                ('cs2638602', models.IntegerField(verbose_name=2)),
                ('ps2638602', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic3_2638602',
            },
        ),
    ]
