# Generated by Django 4.0.5 on 2022-07-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_ic3_2638602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ic3_2638603',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2638603', models.IntegerField(verbose_name=2)),
                ('pe2638603', models.IntegerField(verbose_name=2)),
                ('sk2638603', models.IntegerField(verbose_name=2)),
                ('mt2638603', models.IntegerField(verbose_name=2)),
                ('ms2638603', models.IntegerField(verbose_name=2)),
                ('pa2638603', models.IntegerField(verbose_name=2)),
                ('cs2638603', models.IntegerField(verbose_name=2)),
                ('ps2638603', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic3_2638603',
            },
        ),
        migrations.CreateModel(
            name='Ic3_2638604',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2638604', models.IntegerField(verbose_name=2)),
                ('pe2638604', models.IntegerField(verbose_name=2)),
                ('sk2638604', models.IntegerField(verbose_name=2)),
                ('mt2638604', models.IntegerField(verbose_name=2)),
                ('ms2638604', models.IntegerField(verbose_name=2)),
                ('pa2638604', models.IntegerField(verbose_name=2)),
                ('cs2638604', models.IntegerField(verbose_name=2)),
                ('ps2638604', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic3_2638604',
            },
        ),
        migrations.CreateModel(
            name='Ic3_2638605',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2638605', models.IntegerField(verbose_name=2)),
                ('pe2638605', models.IntegerField(verbose_name=2)),
                ('sk2638605', models.IntegerField(verbose_name=2)),
                ('mt2638605', models.IntegerField(verbose_name=2)),
                ('ms2638605', models.IntegerField(verbose_name=2)),
                ('pa2638605', models.IntegerField(verbose_name=2)),
                ('cs2638605', models.IntegerField(verbose_name=2)),
                ('ps2638605', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic3_2638605',
            },
        ),
    ]
