# Generated by Django 4.0.5 on 2022-07-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_sem_serve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ic3_2638601',
            name='cs2638601',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ic3_2638601',
            name='ms2638601',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ic3_2638601',
            name='mt2638601',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ic3_2638601',
            name='pa2638601',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ic3_2638601',
            name='pe2638601',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='ic3_2638601',
            name='pr2638601',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='ic3_2638601',
            name='ps2638601',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ic3_2638601',
            name='sk2638601',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='ic3_2638601',
            name='std_id',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
