# Generated by Django 4.0.5 on 2022-07-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_ic3_2638601_cs2638601_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ic3_2618601',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2618601', models.IntegerField(verbose_name=2)),
                ('pe2618601', models.IntegerField(verbose_name=2)),
                ('sk2618601', models.IntegerField(verbose_name=2)),
                ('mt2618601', models.IntegerField(verbose_name=2)),
                ('ms2618601', models.IntegerField(verbose_name=2)),
                ('pa2618601', models.IntegerField(verbose_name=2)),
                ('cs2618601', models.IntegerField(verbose_name=2)),
                ('ps2618601', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic3_2618601',
            },
        ),
        migrations.CreateModel(
            name='Ic3_2618602',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2618602', models.IntegerField(verbose_name=2)),
                ('pe2618602', models.IntegerField(verbose_name=2)),
                ('sk2618602', models.IntegerField(verbose_name=2)),
                ('mt2618602', models.IntegerField(verbose_name=2)),
                ('ms2618602', models.IntegerField(verbose_name=2)),
                ('pa2618602', models.IntegerField(verbose_name=2)),
                ('cs2618602', models.IntegerField(verbose_name=2)),
                ('ps2618602', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic3_2618602',
            },
        ),
        migrations.CreateModel(
            name='Ic3_2618603',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2618603', models.IntegerField(verbose_name=2)),
                ('pe2618603', models.IntegerField(verbose_name=2)),
                ('sk2618603', models.IntegerField(verbose_name=2)),
                ('mt2618603', models.IntegerField(verbose_name=2)),
                ('ms2618603', models.IntegerField(verbose_name=2)),
                ('pa2618603', models.IntegerField(verbose_name=2)),
                ('cs2618603', models.IntegerField(verbose_name=2)),
                ('ps2618603', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic3_2618603',
            },
        ),
        migrations.CreateModel(
            name='Ic3_2618604',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2618604', models.IntegerField(verbose_name=2)),
                ('pe2618604', models.IntegerField(verbose_name=2)),
                ('sk2618604', models.IntegerField(verbose_name=2)),
                ('mt2618604', models.IntegerField(verbose_name=2)),
                ('ms2618604', models.IntegerField(verbose_name=2)),
                ('pa2618604', models.IntegerField(verbose_name=2)),
                ('cs2618604', models.IntegerField(verbose_name=2)),
                ('ps2618604', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic3_2618604',
            },
        ),
        migrations.CreateModel(
            name='Ic3_2618605',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2618605', models.IntegerField(verbose_name=2)),
                ('pe2618605', models.IntegerField(verbose_name=2)),
                ('sk2618605', models.IntegerField(verbose_name=2)),
                ('mt2618605', models.IntegerField(verbose_name=2)),
                ('ms2618605', models.IntegerField(verbose_name=2)),
                ('pa2618605', models.IntegerField(verbose_name=2)),
                ('cs2618605', models.IntegerField(verbose_name=2)),
                ('ps2618605', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic3_2618605',
            },
        ),
    ]
