# Generated by Django 4.0.5 on 2022-07-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_ic3_2618602_ic1_2618601_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ic2_2628601',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2628601', models.IntegerField(verbose_name=2)),
                ('pe2628601', models.IntegerField(verbose_name=2)),
                ('sk2628601', models.IntegerField(verbose_name=2)),
                ('mt2628601', models.IntegerField(verbose_name=2)),
                ('ms2628601', models.IntegerField(verbose_name=2)),
                ('pa2628601', models.IntegerField(verbose_name=2)),
                ('cs2628601', models.IntegerField(verbose_name=2)),
                ('ps2628601', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic2_2628601',
            },
        ),
        migrations.CreateModel(
            name='Ic2_2628602',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2628602', models.IntegerField(verbose_name=2)),
                ('pe2628602', models.IntegerField(verbose_name=2)),
                ('sk2628602', models.IntegerField(verbose_name=2)),
                ('mt2628602', models.IntegerField(verbose_name=2)),
                ('ms2628602', models.IntegerField(verbose_name=2)),
                ('pa2628602', models.IntegerField(verbose_name=2)),
                ('cs2628602', models.IntegerField(verbose_name=2)),
                ('ps2628602', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic2_2628602',
            },
        ),
        migrations.CreateModel(
            name='Ic2_2628603',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2628603', models.IntegerField(verbose_name=2)),
                ('pe2628603', models.IntegerField(verbose_name=2)),
                ('sk2628603', models.IntegerField(verbose_name=2)),
                ('mt2628603', models.IntegerField(verbose_name=2)),
                ('ms2628603', models.IntegerField(verbose_name=2)),
                ('pa2628603', models.IntegerField(verbose_name=2)),
                ('cs2628603', models.IntegerField(verbose_name=2)),
                ('ps2628603', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic2_2628603',
            },
        ),
        migrations.CreateModel(
            name='Ic2_2628604',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2628604', models.IntegerField(verbose_name=2)),
                ('pe2628604', models.IntegerField(verbose_name=2)),
                ('sk2628604', models.IntegerField(verbose_name=2)),
                ('mt2628604', models.IntegerField(verbose_name=2)),
                ('ms2628604', models.IntegerField(verbose_name=2)),
                ('pa2628604', models.IntegerField(verbose_name=2)),
                ('cs2628604', models.IntegerField(verbose_name=2)),
                ('ps2628604', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic2_2628604',
            },
        ),
        migrations.CreateModel(
            name='Ic2_2628605',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2628605', models.IntegerField(verbose_name=2)),
                ('pe2628605', models.IntegerField(verbose_name=2)),
                ('sk2628605', models.IntegerField(verbose_name=2)),
                ('mt2628605', models.IntegerField(verbose_name=2)),
                ('ms2628605', models.IntegerField(verbose_name=2)),
                ('pa2628605', models.IntegerField(verbose_name=2)),
                ('cs2628605', models.IntegerField(verbose_name=2)),
                ('ps2628605', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic2_2628605',
            },
        ),
    ]
