# Generated by Django 4.0.5 on 2022-07-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_ic2_2628601_ic2_2628602_ic2_2628603_ic2_2628604_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ic4_2648601',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(default=None, unique=True)),
                ('pr2648601', models.IntegerField(default=None)),
                ('pe2648601', models.IntegerField(default=None)),
                ('sk2648601', models.IntegerField(default=None)),
                ('mt2648601', models.IntegerField(null=True)),
                ('ms2648601', models.IntegerField(null=True)),
                ('pa2648601', models.IntegerField(null=True)),
                ('cs2648601', models.IntegerField(null=True)),
                ('ps2648601', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ic4_2648601',
            },
        ),
        migrations.CreateModel(
            name='Ic4_2648602',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2648602', models.IntegerField(verbose_name=2)),
                ('pe2648602', models.IntegerField(verbose_name=2)),
                ('sk2648602', models.IntegerField(verbose_name=2)),
                ('mt2648602', models.IntegerField(verbose_name=2)),
                ('ms2648602', models.IntegerField(verbose_name=2)),
                ('pa2648602', models.IntegerField(verbose_name=2)),
                ('cs2648602', models.IntegerField(verbose_name=2)),
                ('ps2648602', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic4_2648602',
            },
        ),
        migrations.CreateModel(
            name='Ic4_2648603',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2648603', models.IntegerField(verbose_name=2)),
                ('pe2648603', models.IntegerField(verbose_name=2)),
                ('sk2648603', models.IntegerField(verbose_name=2)),
                ('mt2648603', models.IntegerField(verbose_name=2)),
                ('ms2648603', models.IntegerField(verbose_name=2)),
                ('pa2648603', models.IntegerField(verbose_name=2)),
                ('cs2648603', models.IntegerField(verbose_name=2)),
                ('ps2648603', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic4_2648603',
            },
        ),
        migrations.CreateModel(
            name='Ic4_2648604',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2648604', models.IntegerField(verbose_name=2)),
                ('pe2648604', models.IntegerField(verbose_name=2)),
                ('sk2648604', models.IntegerField(verbose_name=2)),
                ('mt2648604', models.IntegerField(verbose_name=2)),
                ('ms2648604', models.IntegerField(verbose_name=2)),
                ('pa2648604', models.IntegerField(verbose_name=2)),
                ('cs2648604', models.IntegerField(verbose_name=2)),
                ('ps2648604', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic4_2648604',
            },
        ),
        migrations.CreateModel(
            name='Ic4_2648605',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2648605', models.IntegerField(verbose_name=2)),
                ('pe2648605', models.IntegerField(verbose_name=2)),
                ('sk2648605', models.IntegerField(verbose_name=2)),
                ('mt2648605', models.IntegerField(verbose_name=2)),
                ('ms2648605', models.IntegerField(verbose_name=2)),
                ('pa2648605', models.IntegerField(verbose_name=2)),
                ('cs2648605', models.IntegerField(verbose_name=2)),
                ('ps2648605', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic4_2648605',
            },
        ),
    ]
