# Generated by Django 4.0.5 on 2022-07-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_ic4_2648601_ic4_2648602_ic4_2648603_ic4_2648604_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ic5_2658601',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(default=None, unique=True)),
                ('pr2658601', models.IntegerField(default=None)),
                ('pe2658601', models.IntegerField(default=None)),
                ('sk2658601', models.IntegerField(default=None)),
                ('mt2658601', models.IntegerField(null=True)),
                ('ms2658601', models.IntegerField(null=True)),
                ('pa2658601', models.IntegerField(null=True)),
                ('cs2658601', models.IntegerField(null=True)),
                ('ps2658601', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ic5_2658601',
            },
        ),
        migrations.CreateModel(
            name='Ic5_2658602',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2658602', models.IntegerField(verbose_name=2)),
                ('pe2658602', models.IntegerField(verbose_name=2)),
                ('sk2658602', models.IntegerField(verbose_name=2)),
                ('mt2658602', models.IntegerField(verbose_name=2)),
                ('ms2658602', models.IntegerField(verbose_name=2)),
                ('pa2658602', models.IntegerField(verbose_name=2)),
                ('cs2658602', models.IntegerField(verbose_name=2)),
                ('ps2658602', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic5_2658602',
            },
        ),
        migrations.CreateModel(
            name='Ic5_2658603',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2658603', models.IntegerField(verbose_name=2)),
                ('pe2658603', models.IntegerField(verbose_name=2)),
                ('sk2658603', models.IntegerField(verbose_name=2)),
                ('mt2658603', models.IntegerField(verbose_name=2)),
                ('ms2658603', models.IntegerField(verbose_name=2)),
                ('pa2658603', models.IntegerField(verbose_name=2)),
                ('cs2658603', models.IntegerField(verbose_name=2)),
                ('ps2658603', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic5_2658603',
            },
        ),
        migrations.CreateModel(
            name='Ic5_2658604',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2658604', models.IntegerField(verbose_name=2)),
                ('pe2658604', models.IntegerField(verbose_name=2)),
                ('sk2658604', models.IntegerField(verbose_name=2)),
                ('mt2658604', models.IntegerField(verbose_name=2)),
                ('ms2658604', models.IntegerField(verbose_name=2)),
                ('pa2658604', models.IntegerField(verbose_name=2)),
                ('cs2658604', models.IntegerField(verbose_name=2)),
                ('ps2658604', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic5_2658604',
            },
        ),
        migrations.CreateModel(
            name='Ic5_2658605',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2658605', models.IntegerField(verbose_name=2)),
                ('pe2658605', models.IntegerField(verbose_name=2)),
                ('sk2658605', models.IntegerField(verbose_name=2)),
                ('mt2658605', models.IntegerField(verbose_name=2)),
                ('ms2658605', models.IntegerField(verbose_name=2)),
                ('pa2658605', models.IntegerField(verbose_name=2)),
                ('cs2658605', models.IntegerField(verbose_name=2)),
                ('ps2658605', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic5_2658605',
            },
        ),
    ]
