# Generated by Django 4.0.5 on 2022-07-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_ic5_2658601_ic5_2658602_ic5_2658603_ic5_2658604_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ic6_2668601',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(default=None, unique=True)),
                ('pr2668601', models.IntegerField(default=None)),
                ('pe2668601', models.IntegerField(default=None)),
                ('sk2668601', models.IntegerField(default=None)),
                ('mt2668601', models.IntegerField(null=True)),
                ('ms2668601', models.IntegerField(null=True)),
                ('pa2668601', models.IntegerField(null=True)),
                ('cs2668601', models.IntegerField(null=True)),
                ('ps2668601', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ic6_2668601',
            },
        ),
        migrations.CreateModel(
            name='Ic6_2668602',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2668602', models.IntegerField(verbose_name=2)),
                ('pe2668602', models.IntegerField(verbose_name=2)),
                ('sk2668602', models.IntegerField(verbose_name=2)),
                ('mt2668602', models.IntegerField(verbose_name=2)),
                ('ms2668602', models.IntegerField(verbose_name=2)),
                ('pa2668602', models.IntegerField(verbose_name=2)),
                ('cs2668602', models.IntegerField(verbose_name=2)),
                ('ps2668602', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic6_2668602',
            },
        ),
        migrations.CreateModel(
            name='Ic6_2668603',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2668603', models.IntegerField(verbose_name=2)),
                ('pe2668603', models.IntegerField(verbose_name=2)),
                ('sk2668603', models.IntegerField(verbose_name=2)),
                ('mt2668603', models.IntegerField(verbose_name=2)),
                ('ms2668603', models.IntegerField(verbose_name=2)),
                ('pa2668603', models.IntegerField(verbose_name=2)),
                ('cs2668603', models.IntegerField(verbose_name=2)),
                ('ps2668603', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic6_2668603',
            },
        ),
        migrations.CreateModel(
            name='Ic6_2668604',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2668604', models.IntegerField(verbose_name=2)),
                ('pe2668604', models.IntegerField(verbose_name=2)),
                ('sk2668604', models.IntegerField(verbose_name=2)),
                ('mt2668604', models.IntegerField(verbose_name=2)),
                ('ms2668604', models.IntegerField(verbose_name=2)),
                ('pa2668604', models.IntegerField(verbose_name=2)),
                ('cs2668604', models.IntegerField(verbose_name=2)),
                ('ps2668604', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic6_2668604',
            },
        ),
        migrations.CreateModel(
            name='Ic6_2668605',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2668605', models.IntegerField(verbose_name=2)),
                ('pe2668605', models.IntegerField(verbose_name=2)),
                ('sk2668605', models.IntegerField(verbose_name=2)),
                ('mt2668605', models.IntegerField(verbose_name=2)),
                ('ms2668605', models.IntegerField(verbose_name=2)),
                ('pa2668605', models.IntegerField(verbose_name=2)),
                ('cs2668605', models.IntegerField(verbose_name=2)),
                ('ps2668605', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic6_2668605',
            },
        ),
    ]
