# Generated by Django 4.0.5 on 2022-07-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_ic7_2678601_ic7_2678602_ic7_2678603_ic7_2678604_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ic8_2688601',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(default=None, unique=True)),
                ('pr2688601', models.IntegerField(default=None)),
                ('pe2688601', models.IntegerField(default=None)),
                ('sk2688601', models.IntegerField(default=None)),
                ('mt2688601', models.IntegerField(null=True)),
                ('ms2688601', models.IntegerField(null=True)),
                ('pa2688601', models.IntegerField(null=True)),
                ('cs2688601', models.IntegerField(null=True)),
                ('ps2688601', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ic8_2688601',
            },
        ),
        migrations.CreateModel(
            name='Ic8_2688602',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2688602', models.IntegerField(verbose_name=2)),
                ('pe2688602', models.IntegerField(verbose_name=2)),
                ('sk2688602', models.IntegerField(verbose_name=2)),
                ('mt2688602', models.IntegerField(verbose_name=2)),
                ('ms2688602', models.IntegerField(verbose_name=2)),
                ('pa2688602', models.IntegerField(verbose_name=2)),
                ('cs2688602', models.IntegerField(verbose_name=2)),
                ('ps2688602', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic8_2688602',
            },
        ),
        migrations.CreateModel(
            name='Ic8_2688603',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2688603', models.IntegerField(verbose_name=2)),
                ('pe2688603', models.IntegerField(verbose_name=2)),
                ('sk2688603', models.IntegerField(verbose_name=2)),
                ('mt2688603', models.IntegerField(verbose_name=2)),
                ('ms2688603', models.IntegerField(verbose_name=2)),
                ('pa2688603', models.IntegerField(verbose_name=2)),
                ('cs2688603', models.IntegerField(verbose_name=2)),
                ('ps2688603', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic8_2688603',
            },
        ),
        migrations.CreateModel(
            name='Ic8_2688604',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2688604', models.IntegerField(verbose_name=2)),
                ('pe2688604', models.IntegerField(verbose_name=2)),
                ('sk2688604', models.IntegerField(verbose_name=2)),
                ('mt2688604', models.IntegerField(verbose_name=2)),
                ('ms2688604', models.IntegerField(verbose_name=2)),
                ('pa2688604', models.IntegerField(verbose_name=2)),
                ('cs2688604', models.IntegerField(verbose_name=2)),
                ('ps2688604', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic8_2688604',
            },
        ),
        migrations.CreateModel(
            name='Ic8_2688605',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2688605', models.IntegerField(verbose_name=2)),
                ('pe2688605', models.IntegerField(verbose_name=2)),
                ('sk2688605', models.IntegerField(verbose_name=2)),
                ('mt2688605', models.IntegerField(verbose_name=2)),
                ('ms2688605', models.IntegerField(verbose_name=2)),
                ('pa2688605', models.IntegerField(verbose_name=2)),
                ('cs2688605', models.IntegerField(verbose_name=2)),
                ('ps2688605', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic8_2688605',
            },
        ),
        migrations.CreateModel(
            name='Ic8_2688607',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2688607', models.IntegerField(verbose_name=2)),
                ('pe2688607', models.IntegerField(verbose_name=2)),
                ('sk2688607', models.IntegerField(verbose_name=2)),
                ('mt2688607', models.IntegerField(verbose_name=2)),
                ('ms2688607', models.IntegerField(verbose_name=2)),
                ('pa2688607', models.IntegerField(verbose_name=2)),
                ('cs2688607', models.IntegerField(verbose_name=2)),
                ('ps2688607', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic8_2688607',
            },
        ),
    ]
