# Generated by Django 4.0.5 on 2022-07-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_ic8_2688601_ic8_2688602_ic8_2688603_ic8_2688604_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ic9_2698601',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(default=None, unique=True)),
                ('pr2698601', models.IntegerField(default=None)),
                ('pe2698601', models.IntegerField(default=None)),
                ('sk2698601', models.IntegerField(default=None)),
                ('mt2698601', models.IntegerField(null=True)),
                ('ms2698601', models.IntegerField(null=True)),
                ('pa2698601', models.IntegerField(null=True)),
                ('cs2698601', models.IntegerField(null=True)),
                ('ps2698601', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ic9_2698601',
            },
        ),
        migrations.CreateModel(
            name='Ic9_2698602',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2698602', models.IntegerField(verbose_name=2)),
                ('pe2698602', models.IntegerField(verbose_name=2)),
                ('sk2698602', models.IntegerField(verbose_name=2)),
                ('mt2698602', models.IntegerField(verbose_name=2)),
                ('ms2698602', models.IntegerField(verbose_name=2)),
                ('pa2698602', models.IntegerField(verbose_name=2)),
                ('cs2698602', models.IntegerField(verbose_name=2)),
                ('ps2698602', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic9_2698602',
            },
        ),
        migrations.CreateModel(
            name='Ic9_2698603',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2698603', models.IntegerField(verbose_name=2)),
                ('pe2698603', models.IntegerField(verbose_name=2)),
                ('sk2698603', models.IntegerField(verbose_name=2)),
                ('mt2698603', models.IntegerField(verbose_name=2)),
                ('ms2698603', models.IntegerField(verbose_name=2)),
                ('pa2698603', models.IntegerField(verbose_name=2)),
                ('cs2698603', models.IntegerField(verbose_name=2)),
                ('ps2698603', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic9_2698603',
            },
        ),
        migrations.CreateModel(
            name='Ic9_2698604',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2698604', models.IntegerField(verbose_name=2)),
                ('pe2698604', models.IntegerField(verbose_name=2)),
                ('sk2698604', models.IntegerField(verbose_name=2)),
                ('mt2698604', models.IntegerField(verbose_name=2)),
                ('ms2698604', models.IntegerField(verbose_name=2)),
                ('pa2698604', models.IntegerField(verbose_name=2)),
                ('cs2698604', models.IntegerField(verbose_name=2)),
                ('ps2698604', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic9_2698604',
            },
        ),
        migrations.CreateModel(
            name='Ic9_2698605',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2698605', models.IntegerField(verbose_name=2)),
                ('pe2698605', models.IntegerField(verbose_name=2)),
                ('sk2698605', models.IntegerField(verbose_name=2)),
                ('mt2698605', models.IntegerField(verbose_name=2)),
                ('ms2698605', models.IntegerField(verbose_name=2)),
                ('pa2698605', models.IntegerField(verbose_name=2)),
                ('cs2698605', models.IntegerField(verbose_name=2)),
                ('ps2698605', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic9_2698605',
            },
        ),
        migrations.CreateModel(
            name='Ic9_2698607',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr2698607', models.IntegerField(verbose_name=2)),
                ('pe2698607', models.IntegerField(verbose_name=2)),
                ('sk2698607', models.IntegerField(verbose_name=2)),
                ('mt2698607', models.IntegerField(verbose_name=2)),
                ('ms2698607', models.IntegerField(verbose_name=2)),
                ('pa2698607', models.IntegerField(verbose_name=2)),
                ('cs2698607', models.IntegerField(verbose_name=2)),
                ('ps2698607', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic9_2698607',
            },
        ),
    ]
