# Generated by Django 4.0.5 on 2022-07-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_ic9_2698601_ic9_2698602_ic9_2698603_ic9_2698604_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mca1_619401',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(default=None, unique=True)),
                ('pr619401', models.IntegerField(default=None)),
                ('pe619401', models.IntegerField(default=None)),
                ('sk619401', models.IntegerField(default=None)),
                ('mt619401', models.IntegerField(null=True)),
                ('ms619401', models.IntegerField(null=True)),
                ('pa619401', models.IntegerField(null=True)),
                ('cs619401', models.IntegerField(null=True)),
                ('ps619401', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'mca1_619401',
            },
        ),
        migrations.CreateModel(
            name='Mca1_619402',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr619402', models.IntegerField(verbose_name=2)),
                ('pe619402', models.IntegerField(verbose_name=2)),
                ('sk619402', models.IntegerField(verbose_name=2)),
                ('mt619402', models.IntegerField(verbose_name=2)),
                ('ms619402', models.IntegerField(verbose_name=2)),
                ('pa619402', models.IntegerField(verbose_name=2)),
                ('cs619402', models.IntegerField(verbose_name=2)),
                ('ps619402', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca1_619402',
            },
        ),
        migrations.CreateModel(
            name='Mca1_619403',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr619403', models.IntegerField(verbose_name=2)),
                ('pe619403', models.IntegerField(verbose_name=2)),
                ('sk619403', models.IntegerField(verbose_name=2)),
                ('mt619403', models.IntegerField(verbose_name=2)),
                ('ms619403', models.IntegerField(verbose_name=2)),
                ('pa619403', models.IntegerField(verbose_name=2)),
                ('cs619403', models.IntegerField(verbose_name=2)),
                ('ps619403', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca1_619403',
            },
        ),
        migrations.CreateModel(
            name='Mca1_619404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr619404', models.IntegerField(verbose_name=2)),
                ('pe619404', models.IntegerField(verbose_name=2)),
                ('sk619404', models.IntegerField(verbose_name=2)),
                ('mt619404', models.IntegerField(verbose_name=2)),
                ('ms619404', models.IntegerField(verbose_name=2)),
                ('pa619404', models.IntegerField(verbose_name=2)),
                ('cs619404', models.IntegerField(verbose_name=2)),
                ('ps619404', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca1_619404',
            },
        ),
        migrations.CreateModel(
            name='Mca1_619405',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr619405', models.IntegerField(verbose_name=2)),
                ('pe619405', models.IntegerField(verbose_name=2)),
                ('sk619405', models.IntegerField(verbose_name=2)),
                ('mt619405', models.IntegerField(verbose_name=2)),
                ('ms619405', models.IntegerField(verbose_name=2)),
                ('pa619405', models.IntegerField(verbose_name=2)),
                ('cs619405', models.IntegerField(verbose_name=2)),
                ('ps619405', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca1_619405',
            },
        ),
        migrations.CreateModel(
            name='Mca1_619406',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr619406', models.IntegerField(verbose_name=2)),
                ('pe619406', models.IntegerField(verbose_name=2)),
                ('sk619406', models.IntegerField(verbose_name=2)),
                ('mt619406', models.IntegerField(verbose_name=2)),
                ('ms619406', models.IntegerField(verbose_name=2)),
                ('pa619406', models.IntegerField(verbose_name=2)),
                ('cs619406', models.IntegerField(verbose_name=2)),
                ('ps619406', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca1_619406',
            },
        ),
    ]
