# Generated by Django 4.0.5 on 2022-07-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_mca1_619401_mca1_619402_mca1_619403_mca1_619404_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mca2_629401',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(default=None, unique=True)),
                ('pr629401', models.IntegerField(default=None)),
                ('pe629401', models.IntegerField(default=None)),
                ('sk629401', models.IntegerField(default=None)),
                ('mt629401', models.IntegerField(null=True)),
                ('ms629401', models.IntegerField(null=True)),
                ('pa629401', models.IntegerField(null=True)),
                ('cs629401', models.IntegerField(null=True)),
                ('ps629401', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'mca2_629401',
            },
        ),
        migrations.CreateModel(
            name='Mca2_629402',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr629402', models.IntegerField(verbose_name=2)),
                ('pe629402', models.IntegerField(verbose_name=2)),
                ('sk629402', models.IntegerField(verbose_name=2)),
                ('mt629402', models.IntegerField(verbose_name=2)),
                ('ms629402', models.IntegerField(verbose_name=2)),
                ('pa629402', models.IntegerField(verbose_name=2)),
                ('cs629402', models.IntegerField(verbose_name=2)),
                ('ps629402', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca2_629402',
            },
        ),
        migrations.CreateModel(
            name='Mca2_629403',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr629403', models.IntegerField(verbose_name=2)),
                ('pe629403', models.IntegerField(verbose_name=2)),
                ('sk629403', models.IntegerField(verbose_name=2)),
                ('mt629403', models.IntegerField(verbose_name=2)),
                ('ms629403', models.IntegerField(verbose_name=2)),
                ('pa629403', models.IntegerField(verbose_name=2)),
                ('cs629403', models.IntegerField(verbose_name=2)),
                ('ps629403', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca2_629403',
            },
        ),
        migrations.CreateModel(
            name='Mca2_629404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr629404', models.IntegerField(verbose_name=2)),
                ('pe629404', models.IntegerField(verbose_name=2)),
                ('sk629404', models.IntegerField(verbose_name=2)),
                ('mt629404', models.IntegerField(verbose_name=2)),
                ('ms629404', models.IntegerField(verbose_name=2)),
                ('pa629404', models.IntegerField(verbose_name=2)),
                ('cs629404', models.IntegerField(verbose_name=2)),
                ('ps629404', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca2_629404',
            },
        ),
        migrations.CreateModel(
            name='Mca2_629405',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr629405', models.IntegerField(verbose_name=2)),
                ('pe629405', models.IntegerField(verbose_name=2)),
                ('sk629405', models.IntegerField(verbose_name=2)),
                ('mt629405', models.IntegerField(verbose_name=2)),
                ('ms629405', models.IntegerField(verbose_name=2)),
                ('pa629405', models.IntegerField(verbose_name=2)),
                ('cs629405', models.IntegerField(verbose_name=2)),
                ('ps629405', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca2_629405',
            },
        ),
        migrations.CreateModel(
            name='Mca2_629408',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr629408', models.IntegerField(verbose_name=2)),
                ('pe629408', models.IntegerField(verbose_name=2)),
                ('sk629408', models.IntegerField(verbose_name=2)),
                ('mt629408', models.IntegerField(verbose_name=2)),
                ('ms629408', models.IntegerField(verbose_name=2)),
                ('pa629408', models.IntegerField(verbose_name=2)),
                ('cs629408', models.IntegerField(verbose_name=2)),
                ('ps629408', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca2_629408',
            },
        ),
    ]
