# Generated by Django 4.0.5 on 2022-07-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_mca2_629401_mca2_629402_mca2_629403_mca2_629404_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mca3_639401',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(default=None, unique=True)),
                ('pr639401', models.IntegerField(default=None)),
                ('pe639401', models.IntegerField(default=None)),
                ('sk639401', models.IntegerField(default=None)),
                ('mt639401', models.IntegerField(null=True)),
                ('ms639401', models.IntegerField(null=True)),
                ('pa639401', models.IntegerField(null=True)),
                ('cs639401', models.IntegerField(null=True)),
                ('ps639401', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'mca3_639401',
            },
        ),
        migrations.CreateModel(
            name='Mca3_639402',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr639402', models.IntegerField(verbose_name=2)),
                ('pe639402', models.IntegerField(verbose_name=2)),
                ('sk639402', models.IntegerField(verbose_name=2)),
                ('mt639402', models.IntegerField(verbose_name=2)),
                ('ms639402', models.IntegerField(verbose_name=2)),
                ('pa639402', models.IntegerField(verbose_name=2)),
                ('cs639402', models.IntegerField(verbose_name=2)),
                ('ps639402', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca3_639402',
            },
        ),
        migrations.CreateModel(
            name='Mca3_639403',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr639403', models.IntegerField(verbose_name=2)),
                ('pe639403', models.IntegerField(verbose_name=2)),
                ('sk639403', models.IntegerField(verbose_name=2)),
                ('mt639403', models.IntegerField(verbose_name=2)),
                ('ms639403', models.IntegerField(verbose_name=2)),
                ('pa639403', models.IntegerField(verbose_name=2)),
                ('cs639403', models.IntegerField(verbose_name=2)),
                ('ps639403', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca3_639403',
            },
        ),
        migrations.CreateModel(
            name='Mca3_639404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr639404', models.IntegerField(verbose_name=2)),
                ('pe639404', models.IntegerField(verbose_name=2)),
                ('sk639404', models.IntegerField(verbose_name=2)),
                ('mt639404', models.IntegerField(verbose_name=2)),
                ('ms639404', models.IntegerField(verbose_name=2)),
                ('pa639404', models.IntegerField(verbose_name=2)),
                ('cs639404', models.IntegerField(verbose_name=2)),
                ('ps639404', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca3_639404',
            },
        ),
        migrations.CreateModel(
            name='Mca3_639407',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr639407', models.IntegerField(verbose_name=2)),
                ('pe639407', models.IntegerField(verbose_name=2)),
                ('sk639407', models.IntegerField(verbose_name=2)),
                ('mt639407', models.IntegerField(verbose_name=2)),
                ('ms639407', models.IntegerField(verbose_name=2)),
                ('pa639407', models.IntegerField(verbose_name=2)),
                ('cs639407', models.IntegerField(verbose_name=2)),
                ('ps639407', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca3_639407',
            },
        ),
        migrations.CreateModel(
            name='Mca3_639410',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr639410', models.IntegerField(verbose_name=2)),
                ('pe639410', models.IntegerField(verbose_name=2)),
                ('sk639410', models.IntegerField(verbose_name=2)),
                ('mt639410', models.IntegerField(verbose_name=2)),
                ('ms639410', models.IntegerField(verbose_name=2)),
                ('pa639410', models.IntegerField(verbose_name=2)),
                ('cs639410', models.IntegerField(verbose_name=2)),
                ('ps639410', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca3_639410',
            },
        ),
    ]
