# Generated by Django 4.0.5 on 2022-07-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_mca3_639401_mca3_639402_mca3_639403_mca3_639404_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ic10_4401601',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr4401601', models.IntegerField(verbose_name=2)),
                ('pe4401601', models.IntegerField(verbose_name=2)),
                ('sk4401601', models.IntegerField(verbose_name=2)),
                ('mt4401601', models.IntegerField(verbose_name=2)),
                ('ms4401601', models.IntegerField(verbose_name=2)),
                ('pa4401601', models.IntegerField(verbose_name=2)),
                ('cs4401601', models.IntegerField(verbose_name=2)),
                ('ps4401601', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'ic10_4401601',
            },
        ),
    ]
