# Generated by Django 4.0.5 on 2022-07-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_ic10_4401601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mca4_649401',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('pr649401', models.IntegerField(verbose_name=2)),
                ('pe649401', models.IntegerField(verbose_name=2)),
                ('sk649401', models.IntegerField(verbose_name=2)),
                ('mt649401', models.IntegerField(verbose_name=2)),
                ('ms649401', models.IntegerField(verbose_name=2)),
                ('pa649401', models.IntegerField(verbose_name=2)),
                ('cs649401', models.IntegerField(verbose_name=2)),
                ('ps649401', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'mca4_649401',
            },
        ),
    ]
