# Generated by Django 4.0.5 on 2022-07-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_mca4_649401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
