# Generated by Django 4.0.5 on 2022-07-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
